defaults: &defaults
  working_directory: ~/circleci-demo-workflows
  steps:
  - checkout
  - run:
      name: update-npm
      command: 'sudo npm install -g npm@5'
  - restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - run:
      name: install-npm-wee
      command: npm install
  - save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
      - ./node_modules
  - run:
      name: test
      command: echo "passed"
  - run:
      name: check-env
      command: |
        echo $RAILS_ENV
        echo $PGHOST
        echo $PGUSER
        echo $MONGO_ENV
        echo $MONGO_HOST
        echo $MONGO_USER
        pwd
        ls -la

version: 2
jobs:
  "node-4.8.1":
    docker:
    - image: circleci/node:4.8.1
      environment:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        PGUSER: root
    - image: mongo:3.4.4
      environment:
        MONGO_ENV: test
        MONGO_HOST: 127.0.0.1
        MONGO_USER: root
    <<: *defaults

  "node-4.8.2":
    docker:
    - image: circleci/node:4.8.2
    - image: mongo:3.4.4
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
    - "node-4.8.1"
    - "node-4.8.2"
